from selenium import webdriver
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
import time
driver = webdriver.Chrome()
driver.get(url="localhost:8080")
time.sleep(3)
element = driver.find_element_by_name("email")
element.clear()
element.send_keys("james@gmail.com")
element = driver.find_element_by_name("pass")
element.clear()
element.send_keys("iamjames")
element = driver.find_element_by_name("submit")
element.click()
time.sleep(10)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/div[2]/div["
                                       "@class='color-changer']/div[@class='main']/div[@class='name'][3]")
element.click()
time.sleep(2)
driver.get("localhost:8080/app/people/add")
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Девид")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("Паттерсон")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[3]/select"))
element.select_by_value("en")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[4]/input")
element.clear()
element.send_keys("david@gmail.com")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("david")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/input")
element.clear()
element.send_keys("Ютубер")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[8]/select"))
element.select_by_value("Manager")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
driver.get("localhost:8080/app/people/add")
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Эд")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("Бун")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[3]/select"))
element.select_by_value("en")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[4]/input")
element.clear()
element.send_keys("ed@gmail.com")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("iamed")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/input")
element.clear()
element.send_keys("Актёр")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[8]/select"))
element.select_by_value("Worker")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
driver.get("localhost:8080/app/springs/add")
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Grand Tour")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("Автомобильное шоу V2")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("Самые быстрые автомобили на земле")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/input")
element.clear()
element.send_keys("От McLaren F1 до Bugatti Chiron")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[7]/input")
element.clear()
element.send_keys("https://ru.wikipedia.org/wiki/Bugatti_Chiron")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
driver.get("http://localhost:8080/app/tasks")
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Серия 1")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("НОВЫЕ СЕРИИ")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[4]/select"))
element.select_by_value("Low")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("McLaren")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/select"))
element.select_by_visible_text("Девид Паттерсон")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[7]/select"))
element.select_by_visible_text("Grand Tour")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[8]/input")
element.send_keys(Keys.ARROW_LEFT)
element.send_keys(Keys.ARROW_LEFT)
element.send_keys("20062019")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[9]/input")
element.clear()
element.send_keys("15")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[10]/input")
element.clear()
element.send_keys("На будущее!")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[11]/input")
element.clear()
element.send_keys("https://ru.wikipedia.org/wiki/The_Grand_Tour")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Серия 2")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("НОВЫЕ СЕРИИ")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[4]/select"))
element.select_by_value("Lowest")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("Bugatti Chiron")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/select"))
element.select_by_visible_text("Ричард Хаммонд")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[7]/select"))
element.select_by_visible_text("Grand Tour")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[8]/input")
element.send_keys(Keys.ARROW_LEFT)
element.send_keys(Keys.ARROW_LEFT)
element.send_keys("20062019")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[9]/input")
element.clear()
element.send_keys("15")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[10]/input")
element.clear()
element.send_keys("На будущее!")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[11]/input")
element.clear()
element.send_keys("https://ru.wikipedia.org/wiki/The_Grand_Tour")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/div/div[5]/div["
                                       "@class='color-changer']/div[@class='main']/div[1]/div[@class='name'][2]")
element.click()
time.sleep(2)
alert = driver.switch_to.alert
time.sleep(1)
alert.send_keys("https://ru.wikipedia.org/wiki/Bugatti")
time.sleep(3)
alert.accept()
time.sleep(5)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[@class='menu']/div["
                                       "@class='option'][8]/a")
element.click()
time.sleep(2)
alert = driver.switch_to.alert
time.sleep(3)
alert.accept()
driver.close()