from selenium import webdriver
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
import time
driver = webdriver.Chrome()
driver.get(url="localhost:8080")
time.sleep(3)
element = driver.find_element_by_xpath('//a[@href="Register"]')
element.click()
element = driver.find_element_by_name("email")
element.clear()
element.send_keys("jaja.2010")
time.sleep(0.5)
element = driver.find_element_by_name("submit")
element.click()
time.sleep(0.5)
element = driver.find_element_by_name("email")
element.clear()
element.send_keys("jaja.2010@yandex.ru")
time.sleep(0.5)
element = driver.find_element_by_name("pass")
element.send_keys("123")
element = driver.find_element_by_name("submit")
element.click()
time.sleep(0.5)
element = driver.find_element_by_name("pass")
element.clear()
element.send_keys("helloworld")
element = driver.find_element_by_name("confPass")
element.clear()
element.send_keys("hellowrold")
element = driver.find_element_by_name("submit")
element.click()
time.sleep(0.5)
element = driver.find_element_by_name("confPass")
element.clear()
element.send_keys("helloworld")
element = driver.find_element_by_name("submit")
element.click()
time.sleep(15)
alert = driver.switch_to.alert
time.sleep(1)
alert.accept()
time.sleep(3)
element = driver.find_element_by_xpath('//a[@href="Register"]')
element.click()
element = driver.find_element_by_name("email")
element.clear()
element.send_keys("jeremy@gmail.com")
element = driver.find_element_by_name("pass")
element.clear()
element.send_keys("iamjeremy")
element = driver.find_element_by_name("confPass")
element.clear()
element.send_keys("iamjeremy")
element = driver.find_element_by_name("submit")
element.click()
time.sleep(3)
element = driver.find_element_by_name("email")
element.clear()
element.send_keys("jeremy@gmail.com")
element = driver.find_element_by_name("pass")
element.clear()
element.send_keys("iamgermy")
element = driver.find_element_by_name("submit")
element.click()
time.sleep(1)
alert = driver.switch_to.alert
time.sleep(1)
alert.accept()
time.sleep(3)
element = driver.find_element_by_name("email")
element.clear()
element.send_keys("jeremy@gmail.com")
element = driver.find_element_by_name("pass")
element.clear()
element.send_keys("iamjeremy")
element = driver.find_element_by_name("submit")
element.click()
time.sleep(5)
element = driver.find_element_by_name("addProject")
element.click()
time.sleep(3)
element = driver.find_element_by_name("projectName")
element.clear()
element.send_keys("Top Gear")
element = driver.find_element_by_name("projectDesc")
element.clear()
element.send_keys("Компьютерная игра")
element = driver.find_element_by_name("projectPub")
element.click()
element = driver.find_element_by_name("projectGit")
element.clear()
element.send_keys("test")
element = driver.find_element_by_name("submit")
element.click()
time.sleep(5)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/div[2]/div[@class='color-changer']/div[@class='main']/div[@class='name'][3]")
element.click()
time.sleep(2)
driver.get("localhost:8080/app/people/add")
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Джереми")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("Кларксон")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[3]/select"))
element.select_by_value("en")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[4]/input")
element.clear()
element.send_keys("jeremy@gmail.com")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("iamjeremy")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/input")
element.clear()
element.send_keys("Главный")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[7]/input")
element.click()
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
driver.get("localhost:8080/app/people/add")
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Джеймс")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("Мей")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[3]/select"))
element.select_by_value("en")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[4]/input")
element.clear()
element.send_keys("james@gmail.com")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("iamjames")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/input")
element.clear()
element.send_keys("Улитка")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[8]/select"))
element.select_by_value("Manager")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
driver.get("localhost:8080/app/people/add")
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Ричард")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("Хаммонд")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[3]/select"))
element.select_by_value("en")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[4]/input")
element.clear()
element.send_keys("richar@gmail.com")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("iamrichard")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/input")
element.clear()
element.send_keys("Хомяк")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[8]/select"))
element.select_by_value("Worker")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
driver.get("localhost:8080/app/springs/add")
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Top Gear")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("Автомобильное шоу")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("Что такое автомобиль?")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/input")
element.clear()
element.send_keys("История начиная с нулевых")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[7]/input")
element.clear()
element.send_keys("https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
driver.get("http://localhost:8080/app/tasks")
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Серия 1")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("СЕРИИ")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[4]/select"))
element.select_by_value("Highest")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("Форд Мустанг")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/select"))
element.select_by_visible_text("Ричард Хаммонд")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[7]/select"))
element.select_by_visible_text("Top Gear")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[8]/input")
element.send_keys(Keys.ARROW_LEFT)
element.send_keys(Keys.ARROW_LEFT)
element.send_keys("19052019")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[9]/input")
element.clear()
element.send_keys("5")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[10]/input")
element.clear()
element.send_keys("Выполнить как можно скорее!")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[11]/input")
element.clear()
element.send_keys("https://ru.wikipedia.org/wiki/Top_Gear")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Серия 2")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("СЕРИИ")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[4]/select"))
element.select_by_value("Medium")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("Мини Купер")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/select"))
element.select_by_visible_text("Ричард Хаммонд")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[7]/select"))
element.select_by_visible_text("Top Gear")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[8]/input")
element.send_keys(Keys.ARROW_LEFT)
element.send_keys(Keys.ARROW_LEFT)
element.send_keys("19052019")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[9]/input")
element.clear()
element.send_keys("5")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[10]/input")
element.clear()
element.send_keys("Выполнить как можно скорее!")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[11]/input")
element.clear()
element.send_keys("https://ru.wikipedia.org/wiki/Top_Gear")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(2)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[1]/input")
element.clear()
element.send_keys("Серия 3")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[2]/input")
element.clear()
element.send_keys("СЕРИИ")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[4]/select"))
element.select_by_value("Lowest")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[5]/input")
element.clear()
element.send_keys("Феррари")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[6]/select"))
element.select_by_visible_text("Ричард Хаммонд")
element = Select(driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[7]/select"))
element.select_by_visible_text("Top Gear")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[8]/input")
element.send_keys(Keys.ARROW_LEFT)
element.send_keys(Keys.ARROW_LEFT)
element.send_keys("19052019")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[9]/input")
element.clear()
element.send_keys("5")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[10]/input")
element.clear()
element.send_keys("Выполнить как можно скорее!")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/label[11]/input")
element.clear()
element.send_keys("https://ru.wikipedia.org/wiki/Top_Gear")
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/input")
element.click()
time.sleep(5)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[2]/div/div[3]/div["
                                       "@class='color-changer']/div[@class='main']/div[1]/div[@class='name'][2]")
element.click()
time.sleep(2)
alert = driver.switch_to.alert
time.sleep(1)
alert.send_keys("https://ru.wikipedia.org/wiki/Ferrari")
time.sleep(3)
alert.accept()
time.sleep(5)
element = driver.find_element_by_xpath("/html/body/div/main[@class='container']/div[@class='menu']/div[@class='option'][8]/a")
element.click()
time.sleep(2)
alert = driver.switch_to.alert
time.sleep(3)
alert.accept()
time.sleep(3)
driver.close()